name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features alloc"
          - "--features alloc,serde"
          - "--features std"
          - "--features std,serde"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features ${{ matrix.args }}
  clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          - ""
          - "--features alloc"
          - "--features alloc,serde"
          - "--features std"
          - "--features std,serde"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-default-features ${{ matrix.args }} -- -D warnings
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: rustdoc
          args: --features serde -- --cfg doc_cfg -D warnings
